web/mysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic.base import TemplateView, RedirectView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('nonrisk.urls')),
]
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/nonrisk/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # Companies level
    path('', views.companies_view, name='companies_view'),
    path('add/company', views.company_add, name='company_add'),
    path('search/company', views.company_search, name= 'company_search'),
    path('search/patient', views.patient_search, name= 'patient_search'),
    # Company level 
    path('<int:company_id>/edit', views.company_edit, name='company_edit'),
    path('<int:company_id>/delete', views.company_delete, name='company_delete'),
    path('<int:company_id>/patients', views.company_view, name='company_view'),
    path('<int:company_id>/add-patient', views.patient_add, name='patient_add'),
    # Patient level
    path('<int:company_id>/<int:patient_id>', views.patient_view, name='patient_view'),
    path('<int:company_id>/<int:patient_id>/edit', views.patient_edit, name='patient_edit'),
    path('<int:company_id>/<int:patient_id>/delete', views.patient_delete, name='patient_delete'),
    path('<int:company_id>/<int:patient_id>/add', views.study_add, name='study_add'),
    # Study level
    path('<int:company_id>/<int:patient_id>/<int:studies_id>', views.study_view, name='study_view'),
    path('<int:company_id>/<int:patient_id>/<int:studies_id>/pdf', views.export_pdf, name='export_pdf'),
    path('<int:company_id>/<int:patient_id>/<int:studies_id>/edit', views.study_edit, name='study_edit'),
    path('<int:company_id>/<int:patient_id>/<int:studies_id>/delete', views.study_delete, name='study_delete'),
]

web/nonrisk/models.py
from __future__ import unicode_literals
import os, datetime, uuid
import __future__
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _





class Company(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, null=False, blank=False)
    logo = models.ImageField('Logo Photo', upload_to='', null=True, blank=True)
    def __str__(self):
        return self.name


class Patient(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    id = models.IntegerField(primary_key=True) #DNI

    MALE = 'M'
    FEMALE = 'F'
    SEX_OPTIONS = ((MALE, 'Male'), (FEMALE, 'Female'))

    name = models.CharField(max_length=50, null=False, blank=False)
    name_second = models.CharField(max_length=50, null=True, blank=True)
    name_last = models.CharField(max_length=50, null=False, blank=False)
    sex = models.CharField(max_length=1, choices=SEX_OPTIONS)
    address = models.CharField(max_length=175, null=False, blank=False)
    phone = models.IntegerField()
    date_of_birth = models.DateField()
    medical_details = models.CharField(max_length=300)
    
    WHITE = 'W'
    BLACK = 'B'
    RACE_OPTIONS = ((WHITE, 'white'), (BLACK, 'black'))
    race = models.CharField(max_length=1, choices=RACE_OPTIONS, null=False, blank=False)

    arterial_age = models.IntegerField(null=True, blank=True)

    smoke = models.BooleanField()
    smoke_quantity = models.IntegerField(null=True, blank=True)
    smoke_duration = models.DateField(null=True, blank=True)
    smoke_quit = models.DateField(null=True, blank=True)

    diabetes = models.BooleanField()
    diabetes_type = models.IntegerField(null=True, blank=True)
    diabetes_date = models.DateField(null=True, blank=True)

    PRIMARY = 'Primaria'
    SECONDARY = 'Secundaria'
    HYPER_OPTIONS = ((PRIMARY, 'Primaria'),(SECONDARY, 'Secundaria'))
    hyper = models.BooleanField()
    hyper_type = models.CharField(null=True, max_length=10,choices=HYPER_OPTIONS, blank=True)
    hyper_date = models.DateField(null=True, blank=True)

    I = 'I'
    IIA = 'IIa'
    IIB = 'IIb'
    III = 'III'
    IV = 'IV'
    V = 'V'
    DISLIPIDEMIA_OPTIONS = ((I,'I'),(IIA, 'IIa'),(IIB,'IIb'),(III,'III'),
        (IV, 'IV'),(V,'V'))
    dislipidemia = models.BooleanField()
    dislipidemia_type = models.CharField(null=True, max_length=10,
                                         choices=DISLIPIDEMIA_OPTIONS, blank=True)
    dislipidemia_date = models.DateField(null=True, blank=True)
    
    G1 ='G1'
    G2 ='G2'
    G3A='G3a'
    G3B='G3b'
    G4 ='G4'
    G5 ='G5'
    IRC_OPTIONS = ((G1,'G1'),(G2,'G2'),(G3A,'G3a'),(G3B,'G3b'),(G4,'G4'),(G5,'G5'))
    irc = models.BooleanField()
    irc_type = models.CharField(null=True,blank=True, choices=IRC_OPTIONS, max_length=3)

    iam = models.BooleanField()
    acv = models.BooleanField()
    revasc = models.BooleanField()
    enfvp = models.BooleanField()
    acv_ait= models.BooleanField()
    fecvt = models.BooleanField()

    def __str__(self):
        return self.name

class Studies(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    id      = models.AutoField(primary_key=True)
    date    = models.DateField()
    doctor  = models.CharField(max_length=300, blank=True, null=True)

    weight = models.IntegerField() # in kg
    height = models.FloatField()   # in m
    tas    = models.IntegerField()
    tad    = models.IntegerField()
    pulse  = models.IntegerField()

    chol_level = models.IntegerField(null=True,blank=True) #Chol Level
    hdl_level  = models.IntegerField(null=True,blank=True) #TRI Level
    ldl_level  = models.IntegerField(null=True,blank=True) #HDL Level
    tri_level  = models.IntegerField(null=True,blank=True) #LDL Level
    
    glucemia  = models.IntegerField()
    hba1c     = models.FloatField()
    ac_uric   = models.FloatField()
    creat     = models.FloatField()
    tsh       = models.FloatField()
    pcr       = models.FloatField()
    
    renal_filter = models.IntegerField(null=True,blank=True)

    comments = models.CharField(max_length=300, null=True, blank=True)
    photo    = models.ImageField('Studies photo',upload_to = '', null=True, blank=True)
    graphic  = models.ImageField('Graphic photo', upload_to = '', null = True, blank=True)


    
    def __str__(self):
        name = str(self.id)
        return name

# These two auto-delete files from filesystem when they are unneeded:

@receiver(models.signals.post_delete, sender=Studies)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `Studies` object is deleted.
    """
    if instance.photo:
        if os.path.isfile(instance.photo.path):
            os.remove(instance.photo.path)
    if instance.graphic:
        if os.path.isfile(instance.graphic.path):
            os.remove(instance.graphic.path)

web/nonrisk/views.py
import re, math, base64, tkinter, matplotlib, io
from io import *
from PIL import Image
matplotlib.use('Agg')
from matplotlib import pylab
from pylab import *
from django.http import *
from .models import *
from .forms import *
import xhtml2pdf.pisa as pisa
from datetime import date, datetime
from django.template import loader
from weasyprint import HTML, CSS
from reportlab.pdfgen import canvas
from django.http import FileResponse, HttpResponse
from django.db import IntegrityError
from django.views.generic import View
from django.forms.models import model_to_dict
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from dateutil.relativedelta import relativedelta
from django.template.loader import get_template
from django.template.defaulttags import register
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.core.files.base import ContentFile
from django.core.files.images import ImageFile

# NEED TO INSTALL: - PILLOW
#                  - PDFKIT
#                  - REPORTLAB
#                  - xhtml2pdf
#                  - matplotlib
#                  -sudo apt-get install python3-tk
#                  -sudo apt-get install libcairo2-dev
#                  -django-cleanup
#                  -weasyprint


def RepresentsInt(s):
    try: 
        int(s)
        return True
    except ValueError:
        return False

def ageFromDate(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

@register.filter
def get_item(dictionary, key): return dictionary.get(key)

@login_required
def companies_view(request):
    companies_list = Company.objects.all()
    patient_list = Patient.objects.all()

    ammount_patients = 0
    ammount_patients_dict = {}
    for company in companies_list:
        ammount_patients = patient_list.filter(company_id = company.id).count()
        ammount_patients_dict.update({company.id : ammount_patients})
        ammount_patients = 0
    context = {'companies_list':companies_list, 'ammount_patients':ammount_patients_dict}
    return render(request, 'companies.html', context)

@login_required
def company_add(request):
    if request.method == 'POST':
        new_company = Company.objects.create(
            name = request.POST.get('name'))
        new_company.logo=request.FILES['logo']
        new_company.save()

        return redirect('company_view', new_company.id)
    elif request.method == 'GET':
        return(render(request, 'company_add.html'))

@login_required
def company_edit(request, company_id):
    company = Company.objects.filter(id=company_id).values() [:1].get()
    
    if request.method == 'GET':
        context = {'company': company}
        return(render(request, 'company_edit.html',context))
    
    if request.method == 'POST':
        company = Company.objects.filter(id=company_id).get()
        company.name = request.POST.get('name')
        company.save()
        return redirect('company_view', company.id)
            
@login_required
def company_search(request):
    if request.method == 'POST':
        data = request.POST.get('data')
        companies_list = Company.objects.all()

        if RepresentsInt(data): 
            companies_list = list(Company.object.filter(id=data))
        else:  
            companies_list = list(Company.objects.filter(name__startswith=data))
        context = { 'companies_list': companies_list}            
        return render(request, 'company_search.html', context)

# Terminar company_view
@login_required
def company_view(request, company_id):
    company = Company.objects.filter(id=company_id) [:1].get()
    patients_list = Patient.objects.filter(company=company)
    studies_list = Studies.objects.all()
    
    ammount_studies = 0
    ammount_studies_dict = {}
    last_studies_date_dict = {}
    last_studies_date = ''
    for patient in patients_list:
        ammount_studies = studies_list.filter(patient_id= patient.id).count()
        if ammount_studies > 0:
            last_studies_date = studies_list.filter(patient_id= patient.id).order_by('date').last()
            last_studies_date = str(last_studies_date.date)
        else:
            ammount_studies = 0
            last_studies_date = ''    
     
        last_studies_date_dict.update({patient.id : last_studies_date})
        ammount_studies_dict.update({patient.id : ammount_studies})
        last_studies_date = ''
        ammount_studies = 0

    context = {'patients_list': patients_list, 'ammount_studies': ammount_studies_dict,
     'last_studies_date': last_studies_date_dict, 'company':company}
    return render(request,'company.html',context)

@login_required
def company_delete(request, company_id):
        Company.objects.filter(id=company_id).delete()

        return redirect('companies_view')

@login_required
def patient_search(request):
    if request.method == 'POST':
        data = request.POST.get('data')
        studies_list = Studies.objects.all()

        ammount_studies = 0
        ammount_studies_dict = {}
        last_studies_date_dict = {}
        last_studies_date = ''

        if RepresentsInt(data): patient_list = list(Patient.objects.filter(id = data))
        else:
            patient_list = list(Patient.objects.filter(name__startswith= data))
            patient_list.extend(list(Patient.objects.filter(name_last__startswith= data)))

        for patient in patient_list:
            ammount_studies = studies_list.filter(patient_id = patient.id).count()
            if ammount_studies > 0:
                last_studies_date = studies_list.filter(patient_id= patient.id).order_by('date').first()
                last_studies_date = str(last_studies_date.date)
            else:
                ammount_studies = 0
                last_studies_date = ''
            last_studies_date_dict.update({patient.id : last_studies_date})
            ammount_studies_dict.update({patient.id : ammount_studies})
            last_studies_date = ''
            ammount_studies = 0
        context = {'patient_list': patient_list,'ammount_studies': ammount_studies_dict,
            'last_studies_date': last_studies_date_dict}
        return render(request, 'patient_search.html', context)

@login_required
def patient_view(request,company_id, patient_id): 
    try:
        company = Company.objects.filter(id=company_id).values() [:1].get()
        patient = Patient.objects.filter(id=patient_id).values()[:1].get()
        studies_list = Studies.objects.filter(patient_id = patient_id) #List of patient's studies
        context = {'company': company, 'patient':patient, 'studies_list':studies_list,}
    except Patient.DoesNotExist:
        raise Http404("Patient does not exist")
    return render(request, 'patient.html', context)

@login_required
def patient_add(request, company_id):
    company = Company.objects.filter(id=company_id).get()
    try:
        if request.method == 'POST':
            new_patient = Patient.objects.create(
                company = company,
                id = request.POST.get('id'),
                name = request.POST.get('name'),
                name_second= request.POST.get('name_second'),
                name_last= request.POST.get('name_last'),
                sex= request.POST.get('sex'),
                address= request.POST.get('address'),
                phone= request.POST.get('phone'),
                date_of_birth= request.POST.get('date_of_birth'),
                medical_details= request.POST.get('medical_details'),
                race = request.POST.get('race'),
                arterial_age = 0,
                
                smoke= request.POST.get('smoke') == 'on',
                smoke_quantity= None if request.POST.get('smoke_quantity') == '' else request.POST.get('smoke_quantity'),
                smoke_duration= None if request.POST.get('smoke_duration') == '' else request.POST.get('smoke_duration'),
                smoke_quit= None if request.POST.get('smoke_quit') == '' else request.POST.get('smoke_quit'),

                
                diabetes = request.POST.get('diabetes') == 'on',
                diabetes_type= None if request.POST.get('diabetes_type') == '' else request.POST.get('diabetes_type'),
                diabetes_date= None if request.POST.get('diabetes_date') == '' else request.POST.get('diabetes_date'),

                hyper = request.POST.get('hyper') =='on',
                hyper_type= None if request.POST.get('hyper_type') == '' else request.POST.get('hyper_type'),
                hyper_date= None if request.POST.get('hyper_date') == '' else request.POST.get('hyper_date'),

                dislipidemia = request.POST.get('dislipidemia') == 'on',
                dislipidemia_type= None if request.POST.get('dislipidemia_type') == '' else request.POST.get('dislipidemia_type'),
                dislipidemia_date= None if request.POST.get('dislipidemia_date') == '' else request.POST.get('dislipidemia_date'),
                
                irc = request.POST.get('irc') == 'on',
                irc_type= None if request.POST.get('irc_type') == '' else request.POST.get('irc_type'),

                iam = request.POST.get('iam') == 'on',
                acv = request.POST.get('acv') == 'on',
                revasc = request.POST.get('revasc') == 'on',
                enfvp = request.POST.get('enfvp') == 'on',
                acv_ait = request.POST.get('acv_ait') == 'on',
                fecvt = request.POST.get('fecvt') == 'on',
            )

            return redirect('patient_view', company.id, new_patient.id)
        elif request.method == 'GET':
            context = {'company' : company}
            return(render(request, 'patient_add.html', context
                ))
    except IntegrityError:
        return HttpResponse("Patient with the same ID exist")

@login_required

web/nonrisk/templates/companies.html
{% extends 'navbar.html' %}
{% block content %}
{% load static %}
<div class="container-list">
  <body>
    {% if companies_list %}
      <table style="width:100%; top: 0;">
        <tr>
          <th>Entidad</th>
          <th>Cantidad de Pacientes</th>

        </tr>


    {% for company in companies_list %}
      <tr>
        <td style='text-align: center'>
            <a class=" "href="{% url 'company_view' company.id %}"> 
              <img src="{{company.logo.url}}"width="150px" alt="img">
            </a>
          </td>
          <td style='text-align: center'>{{ammount_patients|get_item:company.id}}</td>
      </tr>
    {% endfor %}
      </table>
    {% else %}
    <br>
      <p>No hay Entidades.</p>
    {% endif %}
  </body>
</div>
{% endblock %}

web/nonrisk/templates/company.html
{% extends 'navbar1.html' %}
{% block content %}
{% load static %}
<div class="container-list">
  <body>
    <h4>{{company.name}}</h4>
    {% if patients_list %}
      <table style="width:100%; top: 0;">
        <tr>
          <th>Nombre</th>
          <th>DNI</th>
          <th>Estudios</th>
          <th>Ultimo Estudio</th>
        </tr>


    {% for patient in patients_list %}
      <tr>
        <td style='text-align: left'>
          <a class=" "href="{%url 'patient_view' company.id patient.id%}"> 
            {{ patient.name}} {{patient.name_middle}} {{patient.name_last}}
          </a>
        </td>
        <td>{{patient.id}}</td>
        <td>{{ammount_studies|get_item:patient.id}}</td>
        <td>{{last_studies_date|get_item:patient.id}}</td>
      </tr>
    {% endfor %}
      </table>
    {% else %}
      <p style="padding-left:10%;">No hay pacientes.</p>
    {% endif %}
  </body>
</div>
{% endblock %}

web/nonrisk/templates/company_add.html
{% extends 'navbar.html' %}
{% block content %}
{% load static %}
<form method='POST' enctype="multipart/form-data" action='{% url 'company_add'%}'>
  {% csrf_token %}
  
  <div class="container-list">
    <div style='margin-right:80%;'> <h4>Nueva Entidad </h4></div><br>
    <div>
      <label for='inputName' >Nombre Entidad:</label>
      <input id='inputName' name='name' type="text" placeholder="Nombre"required='' >
    </div>
    <div>
      <label for='logo' >Logo:</label>
      <input id="logo" type="file" name='logo' required=''>
    </div>
  </div>
</form>


{% endblock %}

web/nonrisk/templates/company_edit.html
{% extends 'navbar.html' %}
{% block content %}
{% load static %}
<form method='POST' enctype="multipart/form-data" action='{% url 'company_edit' company.id%}'>
  {% csrf_token %}
  
  <div class="container-list">
    <div style='margin-right:80%;'> <h4>Editar {{company.name}}</h4></div><br>
    <div>
      <label for='inputName' >Nombre Entidad:</label>
      <input id='inputName' name='name' type="text" value='{{company.name}}' >
    </div>
    <!-- <div>
      <label for='logo' >Logo:</label>
      <input id="logo" type="file" name='logo'> 
    </div> -->
  </div>
</form>


{% endblock %}

web/nonrisk/templates/pacient_add.html
{% extends 'navbar.html' %}
{% block content %}
{% load static %}
<form method='POST' action='{% url 'pacient_add'%}'>
  {% csrf_token %}
  
  <div class="container-list">
    <div style='padding:10px;'> <h4>Nuevo Paciente </h4></div><br>
    <div>
      <label for='inputName' >Nombre Completo:</label>
      <input id='inputName' name='name' type="text" placeholder="Nombre"required='' >
      
      <input id='inputSecondName' name='name_second'type="text" placeholder="Segundo Nombre">
      
      <input id='inputLastName' name='name_last' type="text" placeholder="Apellido" required=''>

      <input style='width: 150px;' name='id' min='1000000' max='100000000' type="number" placeholder="DNI" required=''>
    </div>
    <div>
      
      <select id='id_sex' name="sex" required=''>
        <option value='' selected=''> Sexo </option>
        <option value='M'> Masculino </option>
        <option value='F'> Femenino </option>
      </select>

      <select name="race" required=''>
        <option value='' selected=''> Raza </option>
        <option value='W'> Blanca </option>
        <option value='B'> Negra </option>
      </select>

      <input id='inputAddress' name='address' type="text" placeholder="Direccion" required=''>

      <input id='inputPhone' name='phone' min='1000000' type="number" placeholder="Telefono" required=''>
      
      <label for='inputName' >Fecha de Nacimiento:</label>
      <input id='inputBirthDate' name='date_of_birth' type="date" placeholder="Fecha de Nacimiento" required=''>
    </div>
    <div>
      <br>

      <div style='display:inline; margin-top:5px; margin-bottom:10px;'>
        <label for='inputSmoke' style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding: 6px;' >Fumador:</label>
        <input id='inputSmoke' name='smoke' type="checkbox" onclick='unhide("smoke")'>
      <!-- hacer que se despliege -->
        <div id='smoke' style='display:none; overflow:hidden;'>
          <input style='width: 257px' id='inputSmokeQuantity' type="int" placeholder="Cantidad" name='smoke_quantity'>

          <label for='inputSmokeDuration' style='margin: 5px;' >Duración:</label>
          <input style='margin-left: 20px;' type="date" name='smoke_duration'>

          <label for='inputSmokeQuit' style='margin: 5px;'> Finalización: </label>
          <input id='inputSmokeQuit' type="date" placeholder="Fecha de Nacimiento" name='smoke_quit'>
          <br>
        </div>
      </div>
      <!--  -->

      <div style='display:inline; margin-top:5px; margin-bottom:10px;'>
        <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputHyper' >Hipertenso:</label>
        <input id='inputHyper' type="checkbox" name='hyper' onclick='unhide("hyper")'>
      <!-- Despliege -->
        <div id='hyper' style='display:none; overflow:hidden;'>
          <select style='width:283px;' name="hyper_type">
            <option value='' selected=''> Tipo </option>
            <option value='Primaria'> Primaria  </option>
            <option value='Secundaria'> Secundaria </option>
          </select>

          <label for='inputHyperDate' style='margin: 5px;' >Fecha de Inicio:</label>
          <input id='inputHyperDate' type="date" name='hyper_date'>
          <br>
      </div>
      <!--  -->
      </div>

      <div style='display:inline; margin-top:5px; margin-bottom:10px;'>
        <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputDislipidemia' >Dislipidemia:</label>
        <input id='inputDislipidemia' name='displidemia' type="checkbox" onclick='unhide("dislipidemia")'>
      <!-- Despliege -->
        <div id='dislipidemia' style='width:1200px; display:none; overflow:hidden;'>
          <select style='width:284px;' name="dislipidemia_type">
            <option value='' selected=''> Tipo </option>
            <option value='I'> I  </option>
            <option value='IIa'> IIa </option>
            <option value='IIb'> IIb </option>
            <option value='III'> III </option>
            <option value='IV'> IV </option>
            <option value='V'> V </option>
          </select>

          <label for='inputDislipidemiaDate' style='margin: 5px;' >Fecha de Inicio:</label>
          <input id='inputDislipidemiaDate' name='dispilidemia_date' type="date">
          <br>
        </div>
      <!--  -->
      </div>
      
      <div style='display:inline; margin-top:5px; margin-bottom:10px;'>
        <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputIRC'>IRC:</label>
        <input id='inputIRC' name='irc' type="checkbox" onclick='unhide("irc")'>
      <!-- Despliege -->
        <div id='irc' style='display:none;'>

          <select style='width:284px;' name="irc_type">
            <option value='' selected=''> Tipo </option>
            <option value='G1'> G1  </option>
            <option value='G2'> G2 </option>
            <option value='G3a'> G3a </option>
            <option value='G3b'> G3b </option>
            <option value='G4'> G4 </option>
            <option value='G5'> G5 </option>
          </select>
            <label for='inputIRCDate' style='margin: 5px;'>Fecha de Inicio:</label>
            <input id='inputIRCDate' type="date" name='irc_date'>
          <br>
        </div>
      </div>
      
      <div style='display:inline;width:1200px; margin-top:5px; margin-bottom:10px;'>
        <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputDiabetes'>Diabetes:</label>
        <input id='inputDiabetes' type="checkbox" name='diabetes' onclick='unhide("diabetes")'>
      <!-- Desplegar -->
        <div id='diabetes' style='display:none;'>

          <select style='width:284px;' name="diabetes_type">
            <option value='' selected=''> Tipo </option>
            <option value='1'> 1  </option>
            <option value='2'> 2 </option>
            <option value='3'> 3 </option>
            <option value='4'> 4 </option>
            <option value='5'> 5 </option>
          </select>
          <label for='inputDiabetesDate' style='margin: 5px;'>Fecha de Inicio:</label>
          <input id='inputDiabetesDate' type="date" name='diabetes_date'>
          <br>
        </div>
      </div>
    </div>
    <!--  -->
    <div style='height:92px; width:1238px; display: block;'>
      <br>
      <div style='display:contents'>
    <div style='width:300px; display:inline'>
      <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputIAM'>Antecedentes IAM:</label>
      <input id='inputIAM' type="checkbox" name='iam'>

      <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputACV'>Antecedentes ACV:</label>
      <input id='inputACV' type="checkbox" name='acv'>
    </div>
    
    <div style='width:300px; display:inline'>
      <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputRevasc'>Antecedentes Revasc:</label>
      <input id='inputRevasc' type="checkbox" name='revasc'> 

      <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputEnfvp'>Antecedentes Enf VP:</label>
      <input id='inputEnfvp' type="checkbox" name='enfvp'>
    </div>
    
    <div style='width:300px; display:inline'>
      <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputAcv_ait'>Antecedentes ACV-AIT:</label>
      <input id='inputAcv_ait' type="checkbox" name='acv_ait'>

      <label style='background: rgba(0, 0, 0, 0.05); border-radius: 5px; padding:7px' for='inputFecvt'>Antecedentes FECVT:</label>
      <input id='inputFecvt' type="checkbox" name='fecvt'>
    </div>
    </div>
    </div>
    <!-- <input style='width:100%;' id='inputMedicalDetails' type="text" placeholder="Detalles medicos" name='medical_details'> -->
    <div>
    <label>Detalles médicos:</label><br>
    <textarea style='background-color: #e0dddd;' rows="4" cols="50" name="medical_details"></textarea>
    </div>
    
    <div style='width:100%; text-align: center;'>
    <button type="submit">Guardar</button>
    </div>

  </div>
</form>
<script>
function unhide(id) {
    var x = document.getElementById(id);
    if (x.style.display === "none") {
        x.style.display = "inline";
        x.style.width = "100%"
    } else {
        x.style.display = "none";
    }
}
</script>


{% endblock %}


<!--       <input style='width:70px' id='inputDiabetesType' type="int" placeholder="Tipo">

      <input style='width:120px' id='inputDiabetesCHOLLevel' type="int" placeholder="Nivel de CHOL">

      <input style='width:110px' id='inputDiabetesHDLLevel' type="int" placeholder="Nivel de HDL">

      <input style='width:110px' id='inputDiabetesLDLLevel' type="int" placeholder="Nivel de LDL">

      <input style='width:110px' id='inputDiabetesTRILevel' type="int" placeholder="Nivel de TRI"> -->

web/nonrisk/templates/pacients.html
{% extends 'navbar.html' %}
{% block content %}
{% load static %}
<div class="container-list">
  <body>
    {% if pacients_list %}
      <table style="width:100%; top: 0;">
        <tr>
          <th>Nombre</th>
          <th>DNI</th>
          <th>Estudios</th>
          <th>Ultimo Estudio</th>
        </tr>


    {% for pacient in pacients_list %}
      <tr>
        <td style='text-align: left'>
          <a class=" "href="/pacient/{{ pacient.id }}"> {{ pacient.name}} {{pacient.name_middle}} {{pacient.name_last}}
          </a>
        </td>
        <td>{{pacient.id}}</td>
        <td>{{ammount_studies|get_item:pacient.id}}</td>
        <td>{{last_studies_date|get_item:pacient.id}}</td>
      </tr>
    {% endfor %}
      </table>
    {% else %}
      <p>No hay pacientes.</p>
    {% endif %}
  </body>
</div>
{% endblock %}